const express = require('express');
const router =express.Router();
const checkAuth = require('../middleware/check-auth');
const ProductsController = require('../controllers/products');
router.get("/", ProductsController.products_get_all);
router.post("/",ProductsController.products_create_product);
router.get("/:product",ProductsController.products_get_product);
router.patch("/:product",ProductsController.products_updated_product);
router.delete("/:product",ProductsController.products_delete);
module.exports=router;