const express=require('express');
const router =express.Router();
const checkAuth = require('../middleware/check-auth');
const UserController =require('../controllers/user');
router.post("/signup",UserController.user_signup);
router.post("/login",UserController.user_login);
router.delete("/:userId",UserController.user_delete);
router.post("/aouth/google",UserController.googleuser_signin);
router.post("/aouth/facebook",UserController.fbuser_signup);
module.exports=router;